### ISSUE TITLE
Memory did not validate. Did you erase?

### ISSUE THREAD

**Issue by hebah309** [qmk/qmk_toolbox#265] opened 2021-05-24 21:25 UTC
I tried to flas the configuration that I did using QMK Configurator website for my DZ60 rgb v2
I got the following error 

*** Atmel DFU device connected: ATMEL ATm32U4DFU (03EB:2FF4:0000)
*** Attempting to flash, please don't remove device
>>> dfu-programmer atmega32u4 erase --force
    Erasing flash...  Success
    Checking memory from 0x0 to 0x6FFF...  Not blank at 0x1.
>>> dfu-programmer atmega32u4 flash --force /Users/<user>/Downloads/dztech_dz60rgb_v2_default_B8E6AA3A.hex
    0%                            100%  Programming 0x6580 bytes...
    [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]  Success
    0%                            100%  Reading 0x7000 bytes...
    [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]  Success
    Validating...  ERROR
    25881 invalid bytes in program region, 2677 outside region.
    FAIL
    Memory did not validate. Did you erase?

**Comment by fauxpark** [comment] 2021-05-25 00:43
Duplicate of #234

**Closed by fauxpark** 2021-05-25 00:43 UTC
