### ISSUE TITLE
Mac app missing signature "can’t be opened because Apple cannot check it for malicious software"

### ISSUE THREAD

**Issue by rsms** [qmk/qmk_toolbox#318] opened 2021-11-24 19:04 UTC
Repro:

1. Download "QMK Toolbox.app" release 0.1.1
2. Make sure you "allow apps downloaded from app store and identified developers" in system preferences → security & privacy
3. Right-click the app bundle and select "open" from the menu

Expected: "signature warning" with an "open anyways" button which when tapped cause the app to launch.

Actual: system error message saying "QMK Toolbox.app can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information".

Usually macOS will show a dialog with a warning and allow you to open the app anyways (for unsigned apps), but for some reason that is not available for this app. I am able to run it from the command line though and after trying to open it, it appears with a message in system preferences → security & privacy.

<img width="532" alt="Screen Shot 2021-11-24 at 09 48 43" src="https://user-images.githubusercontent.com/47046/143297968-5c63ee9b-8fcd-478d-93af-0954d6f1f1ac.png">

 - Operating system: macOS 10.15.7 (19H1323)
 - QMK Toolbox version: 0.1.1

**Comment by fauxpark** [comment] 2021-11-25 01:14
Duplicate of #227

**Closed by fauxpark** 2021-11-25 01:14 UTC
