### ISSUE TITLE
Windows Toolbox crashes with "Unhandled Exception" if DFU driver is missing

### ISSUE THREAD

**Issue by nooges** [qmk/qmk_toolbox#92] opened 2019-06-09 20:09 UTC
## Describe the Bug

If the bootloader driver is missing for some MCUs, QMK Toolbox crashes.

## System Information

 - Operating system: Windows
 - QMK Toolbox version: 

## TODO:

Handle the exception and prompt user to install DFU driver for the board using Zadig.

**Comment by drashna** [comment] 2019-06-12 16:44
Better would be if we force installed the correct driver, at that point.  Which is possible, IIRC.  I think that Wally 1.0.1 is doing that.

**Comment by fauxpark** [comment] 2019-09-17 02:49
Duplicate of #61

**Comment by drashna** [comment] 2019-10-01 09:17
This still happening?

**Closed** 2019-10-27 00:14 UTC
